version: '3'

services:
  todo2021_server:
    build:
      context: .
      dockerfile: Dockerfile
    image: todo2021server_image
    container_name: todo2021server_container
    restart: unless-stopped
#    env_file: .env
#    environment:
#      - MONGO_USERNAME=$MONGO_USERNAME
#      - MONGO_PASSWORD=$MONGO_PASSWORD
#      - MONGO_HOSTNAME=db
#      - MONGO_PORT=$MONGO_PORT
#      - MONGO_DB=$MONGO_DB
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
#    command: ./wait-for.sh db:27017 -- yarn dev
    command: yarn dev

  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
#    env_file: .env
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
#      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
